name: Telegram News Auto

on:
  workflow_dispatch:

  schedule:
    # 每天北京时间上午10点运行
    - cron: "0 2 * * *"


jobs:

  run:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"


    - name: Install
      run: |
        pip install -r requirements.txt


    - name: Run
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        CHAT_ID: ${{ secrets.CHAT_ID }}

      run: |
        python main.py
